/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.6
 *
 * Copyright (c) 2015 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtCore.h"

#line 30 "/home/youngben/Gitproject/Python/PyQt-gpl-5.4.1/sip/QtCore/qmetatype.sip"
#include <qmetatype.h>
#line 29 "/home/youngben/Gitproject/Python/PyQt-gpl-5.4.1/QtCore/sipQtCoreQMetaType.cpp"

#line 26 "/home/youngben/Gitproject/Python/PyQt-gpl-5.4.1/sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 33 "/home/youngben/Gitproject/Python/PyQt-gpl-5.4.1/QtCore/sipQtCoreQMetaType.cpp"
#line 30 "/home/youngben/Gitproject/Python/PyQt-gpl-5.4.1/sip/QtCore/qmetatype.sip"
#include <qmetatype.h>
#line 36 "/home/youngben/Gitproject/Python/PyQt-gpl-5.4.1/QtCore/sipQtCoreQMetaType.cpp"


PyDoc_STRVAR(doc_QMetaType_type, "QMetaType.type(str) -> int");

extern "C" {static PyObject *meth_QMetaType_type(PyObject *, PyObject *);}
static PyObject *meth_QMetaType_type(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char* a0;
        PyObject *a0Keep;

        if (sipParseArgs(&sipParseErr, sipArgs, "AA", &a0Keep, &a0))
        {
            int sipRes;

            sipRes = QMetaType::type(a0);
            Py_DECREF(a0Keep);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMetaType, sipName_type, doc_QMetaType_type);

    return NULL;
}


PyDoc_STRVAR(doc_QMetaType_typeName, "QMetaType.typeName(int) -> str");

extern "C" {static PyObject *meth_QMetaType_typeName(PyObject *, PyObject *);}
static PyObject *meth_QMetaType_typeName(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "i", &a0))
        {
            const char*sipRes;

            sipRes = QMetaType::typeName(a0);

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return PyUnicode_DecodeASCII(sipRes, strlen(sipRes), NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMetaType, sipName_typeName, doc_QMetaType_typeName);

    return NULL;
}


PyDoc_STRVAR(doc_QMetaType_isRegistered, "QMetaType.isRegistered(int) -> bool\n"
    "QMetaType.isRegistered() -> bool");

extern "C" {static PyObject *meth_QMetaType_isRegistered(PyObject *, PyObject *);}
static PyObject *meth_QMetaType_isRegistered(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "i", &a0))
        {
            bool sipRes;

            sipRes = QMetaType::isRegistered(a0);

            return PyBool_FromLong(sipRes);
        }
    }

    {
        const QMetaType *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMetaType, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isRegistered();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMetaType, sipName_isRegistered, doc_QMetaType_isRegistered);

    return NULL;
}


PyDoc_STRVAR(doc_QMetaType_typeFlags, "QMetaType.typeFlags(int) -> QMetaType.TypeFlags");

extern "C" {static PyObject *meth_QMetaType_typeFlags(PyObject *, PyObject *);}
static PyObject *meth_QMetaType_typeFlags(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "i", &a0))
        {
            QMetaType::TypeFlags*sipRes;

            sipRes = new QMetaType::TypeFlags(QMetaType::typeFlags(a0));

            return sipConvertFromNewType(sipRes,sipType_QMetaType_TypeFlags,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMetaType, sipName_typeFlags, doc_QMetaType_typeFlags);

    return NULL;
}


PyDoc_STRVAR(doc_QMetaType_isValid, "QMetaType.isValid() -> bool");

extern "C" {static PyObject *meth_QMetaType_isValid(PyObject *, PyObject *);}
static PyObject *meth_QMetaType_isValid(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QMetaType *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMetaType, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isValid();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMetaType, sipName_isValid, doc_QMetaType_isValid);

    return NULL;
}


PyDoc_STRVAR(doc_QMetaType_flags, "QMetaType.flags() -> QMetaType.TypeFlags");

extern "C" {static PyObject *meth_QMetaType_flags(PyObject *, PyObject *);}
static PyObject *meth_QMetaType_flags(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QMetaType *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QMetaType, &sipCpp))
        {
            QMetaType::TypeFlags*sipRes;

            sipRes = new QMetaType::TypeFlags(sipCpp->flags());

            return sipConvertFromNewType(sipRes,sipType_QMetaType_TypeFlags,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMetaType, sipName_flags, doc_QMetaType_flags);

    return NULL;
}


PyDoc_STRVAR(doc_QMetaType_metaObjectForType, "QMetaType.metaObjectForType(int) -> QMetaObject");

extern "C" {static PyObject *meth_QMetaType_metaObjectForType(PyObject *, PyObject *);}
static PyObject *meth_QMetaType_metaObjectForType(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "i", &a0))
        {
            const QMetaObject*sipRes;

            sipRes = QMetaType::metaObjectForType(a0);

            return sipConvertFromType(const_cast<QMetaObject *>(sipRes),sipType_QMetaObject,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMetaType, sipName_metaObjectForType, doc_QMetaType_metaObjectForType);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QMetaType(void *, const sipTypeDef *);}
static void *cast_QMetaType(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_QMetaType)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QMetaType(void *, int);}
static void release_QMetaType(void *sipCppV,int)
{
    delete reinterpret_cast<QMetaType *>(sipCppV);
}


extern "C" {static void dealloc_QMetaType(sipSimpleWrapper *);}
static void dealloc_QMetaType(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QMetaType(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_type_QMetaType(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QMetaType(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QMetaType *sipCpp = 0;

    {
        int a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "i", &a0))
        {
            sipCpp = new QMetaType(a0);

            return sipCpp;
        }
    }

    return NULL;
}


static PyMethodDef methods_QMetaType[] = {
    {SIP_MLNAME_CAST(sipName_flags), meth_QMetaType_flags, METH_VARARGS, SIP_MLDOC_CAST(doc_QMetaType_flags)},
    {SIP_MLNAME_CAST(sipName_isRegistered), meth_QMetaType_isRegistered, METH_VARARGS, SIP_MLDOC_CAST(doc_QMetaType_isRegistered)},
    {SIP_MLNAME_CAST(sipName_isValid), meth_QMetaType_isValid, METH_VARARGS, SIP_MLDOC_CAST(doc_QMetaType_isValid)},
    {SIP_MLNAME_CAST(sipName_metaObjectForType), meth_QMetaType_metaObjectForType, METH_VARARGS, SIP_MLDOC_CAST(doc_QMetaType_metaObjectForType)},
    {SIP_MLNAME_CAST(sipName_type), meth_QMetaType_type, METH_VARARGS, SIP_MLDOC_CAST(doc_QMetaType_type)},
    {SIP_MLNAME_CAST(sipName_typeFlags), meth_QMetaType_typeFlags, METH_VARARGS, SIP_MLDOC_CAST(doc_QMetaType_typeFlags)},
    {SIP_MLNAME_CAST(sipName_typeName), meth_QMetaType_typeName, METH_VARARGS, SIP_MLDOC_CAST(doc_QMetaType_typeName)}
};

static sipEnumMemberDef enummembers_QMetaType[] = {
    {sipName_Bool, static_cast<int>(QMetaType::Bool), 148},
    {sipName_Char, static_cast<int>(QMetaType::Char), 148},
    {sipName_Double, static_cast<int>(QMetaType::Double), 148},
    {sipName_FirstGuiType, static_cast<int>(QMetaType::FirstGuiType), 148},
    {sipName_Float, static_cast<int>(QMetaType::Float), 148},
    {sipName_Int, static_cast<int>(QMetaType::Int), 148},
    {sipName_LastCoreType, static_cast<int>(QMetaType::LastCoreType), 148},
    {sipName_Long, static_cast<int>(QMetaType::Long), 148},
    {sipName_LongLong, static_cast<int>(QMetaType::LongLong), 148},
    {sipName_MovableType, static_cast<int>(QMetaType::MovableType), 149},
    {sipName_NeedsConstruction, static_cast<int>(QMetaType::NeedsConstruction), 149},
    {sipName_NeedsDestruction, static_cast<int>(QMetaType::NeedsDestruction), 149},
    {sipName_QBitArray, static_cast<int>(QMetaType::QBitArray), 148},
    {sipName_QBitmap, static_cast<int>(QMetaType::QBitmap), 148},
    {sipName_QBrush, static_cast<int>(QMetaType::QBrush), 148},
    {sipName_QByteArray, static_cast<int>(QMetaType::QByteArray), 148},
    {sipName_QChar, static_cast<int>(QMetaType::QChar), 148},
    {sipName_QColor, static_cast<int>(QMetaType::QColor), 148},
    {sipName_QCursor, static_cast<int>(QMetaType::QCursor), 148},
    {sipName_QDate, static_cast<int>(QMetaType::QDate), 148},
    {sipName_QDateTime, static_cast<int>(QMetaType::QDateTime), 148},
    {sipName_QEasingCurve, static_cast<int>(QMetaType::QEasingCurve), 148},
    {sipName_QFont, static_cast<int>(QMetaType::QFont), 148},
    {sipName_QIcon, static_cast<int>(QMetaType::QIcon), 148},
    {sipName_QImage, static_cast<int>(QMetaType::QImage), 148},
    {sipName_QJsonArray, static_cast<int>(QMetaType::QJsonArray), 148},
    {sipName_QJsonDocument, static_cast<int>(QMetaType::QJsonDocument), 148},
    {sipName_QJsonObject, static_cast<int>(QMetaType::QJsonObject), 148},
    {sipName_QJsonValue, static_cast<int>(QMetaType::QJsonValue), 148},
    {sipName_QKeySequence, static_cast<int>(QMetaType::QKeySequence), 148},
    {sipName_QLine, static_cast<int>(QMetaType::QLine), 148},
    {sipName_QLineF, static_cast<int>(QMetaType::QLineF), 148},
    {sipName_QLocale, static_cast<int>(QMetaType::QLocale), 148},
    {sipName_QMatrix, static_cast<int>(QMetaType::QMatrix), 148},
    {sipName_QMatrix4x4, static_cast<int>(QMetaType::QMatrix4x4), 148},
    {sipName_QModelIndex, static_cast<int>(QMetaType::QModelIndex), 148},
    {sipName_QObjectStar, static_cast<int>(QMetaType::QObjectStar), 148},
    {sipName_QPalette, static_cast<int>(QMetaType::QPalette), 148},
    {sipName_QPen, static_cast<int>(QMetaType::QPen), 148},
    {sipName_QPixmap, static_cast<int>(QMetaType::QPixmap), 148},
    {sipName_QPoint, static_cast<int>(QMetaType::QPoint), 148},
    {sipName_QPointF, static_cast<int>(QMetaType::QPointF), 148},
    {sipName_QPolygon, static_cast<int>(QMetaType::QPolygon), 148},
    {sipName_QPolygonF, static_cast<int>(QMetaType::QPolygonF), 148},
    {sipName_QQuaternion, static_cast<int>(QMetaType::QQuaternion), 148},
    {sipName_QRect, static_cast<int>(QMetaType::QRect), 148},
    {sipName_QRectF, static_cast<int>(QMetaType::QRectF), 148},
    {sipName_QRegExp, static_cast<int>(QMetaType::QRegExp), 148},
    {sipName_QRegion, static_cast<int>(QMetaType::QRegion), 148},
    {sipName_QRegularExpression, static_cast<int>(QMetaType::QRegularExpression), 148},
    {sipName_QSize, static_cast<int>(QMetaType::QSize), 148},
    {sipName_QSizeF, static_cast<int>(QMetaType::QSizeF), 148},
    {sipName_QSizePolicy, static_cast<int>(QMetaType::QSizePolicy), 148},
    {sipName_QString, static_cast<int>(QMetaType::QString), 148},
    {sipName_QStringList, static_cast<int>(QMetaType::QStringList), 148},
    {sipName_QTextFormat, static_cast<int>(QMetaType::QTextFormat), 148},
    {sipName_QTextLength, static_cast<int>(QMetaType::QTextLength), 148},
    {sipName_QTime, static_cast<int>(QMetaType::QTime), 148},
    {sipName_QTransform, static_cast<int>(QMetaType::QTransform), 148},
    {sipName_QUrl, static_cast<int>(QMetaType::QUrl), 148},
    {sipName_QUuid, static_cast<int>(QMetaType::QUuid), 148},
    {sipName_QVariant, static_cast<int>(QMetaType::QVariant), 148},
    {sipName_QVariantHash, static_cast<int>(QMetaType::QVariantHash), 148},
    {sipName_QVariantList, static_cast<int>(QMetaType::QVariantList), 148},
    {sipName_QVariantMap, static_cast<int>(QMetaType::QVariantMap), 148},
    {sipName_QVector2D, static_cast<int>(QMetaType::QVector2D), 148},
    {sipName_QVector3D, static_cast<int>(QMetaType::QVector3D), 148},
    {sipName_QVector4D, static_cast<int>(QMetaType::QVector4D), 148},
    {sipName_SChar, static_cast<int>(QMetaType::SChar), 148},
    {sipName_Short, static_cast<int>(QMetaType::Short), 148},
    {sipName_UChar, static_cast<int>(QMetaType::UChar), 148},
    {sipName_UInt, static_cast<int>(QMetaType::UInt), 148},
    {sipName_ULong, static_cast<int>(QMetaType::ULong), 148},
    {sipName_ULongLong, static_cast<int>(QMetaType::ULongLong), 148},
    {sipName_UShort, static_cast<int>(QMetaType::UShort), 148},
    {sipName_UnknownType, static_cast<int>(QMetaType::UnknownType), 148},
    {sipName_User, static_cast<int>(QMetaType::User), 148},
    {sipName_Void, static_cast<int>(QMetaType::Void), 148},
    {sipName_VoidStar, static_cast<int>(QMetaType::VoidStar), 148},
};

PyDoc_STRVAR(doc_QMetaType, "\1QMetaType(int)");


pyqt5ClassTypeDef sipTypeDef_QtCore_QMetaType = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QMetaType,
        {0}
    },
    {
        sipNameNr_QMetaType,
        {0, 0, 1},
        7, methods_QMetaType,
        79, enummembers_QMetaType,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QMetaType,
    sipNameNr_PyQt5_QtCore_pyqtWrapperType,
    sipNameNr_sip_simplewrapper,
    0,
    0,
    init_type_QMetaType,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QMetaType,
    0,
    0,
    0,
    release_QMetaType,
    cast_QMetaType,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0,
    0
};
